# import Library

In [1]:
import numpy as np

# Neural Net class

In [3]:
class NeuralNet():
    
    
    def __init__(self):
        self.input_shape = -1
        self.out_put_shape = -1
        self.batch_size = -1
        self.layer_count = 0
        self.layer_unit_dict = {}
        self.weight_matrix_dict = {}
        
        
    def add(self, unit):
        self.layer_count += 1
        self.layer_unit_dict[self.layer_count] = unit
        
        
#         入力　Keyエラーになるで 
        row    = self.layer_unit_dict[self.layer_count-1] #pre layer
        column = self.layer_unit_dict[self.layer_count]   #current layer
        weight_matrix = np.array([[1 for j in range(column)]for i in range(row)])
        self.weight_matrix_dict[self.layer_count-1] = 
    
    def _compile(self):
        dami = 0
        
        
    def learn(self, x_train, y_train, batch_size,srides, epochs):
        
        
        for epoch in range(epochs):
            for batch in range(batch_size):
                x, y = x_train[batch*sride : (batch+1)*sride], y_train[batch*sride : (batch+1)*sride]  
                
        
    
    def fit(self, x_train, y_train, batch_size, epochs):
        data_size = x_train.shape[0]
        input_size = x_train.shape[1]
        output_size = y_train.shape[1]
        srides = data_size//batch_size
        
        if data_size != y_train.shape[0]:
            raise Exception("Inconsist shape error")
            
        self.layer_unit_dict[0] = input_size
        self.learn(x_train, y_train, srides, epochs)
        
        
    
    def evaluate(self):
        dami = 0
        
    

# Optimizer class

In [ ]:
class optimizer():
    
    
    def __init__(self):
        

In [5]:
if 1!=0:
    raise Exception("Inconsistent shape error")

Exception: Inconsistent shape error

In [7]:
_dict = {}
_dict[0] = 1
_dict

{0: 1}

In [27]:
a = np.array([0,1,2])# 1 x 3
b = np.array([[0,1,2,4],[0,1,2,4],[0,1,2,4]])# 3 x 4
a @ b # 1 x 4 (1x3 3x4)
# array([ 0,  3,  6, 12])

array([ 0,  3,  6, 12])

In [30]:
a.T, b.shape

(array([0, 1, 2]), (3, 4))

In [20]:
b.T

array([0, 1, 2, 4])

In [22]:
c = np.zeros(3)

In [23]:
c

array([0., 0., 0.])

In [25]:
b = np.array([[0,1,2,4],[0,1,2,4],[0,1,2,4]])
b.shape

(3, 4)

In [34]:
d = np.array([[1 for i in range(2)] for j in range(3)])
d

array([[1, 1],
       [1, 1],
       [1, 1]])

In [35]:
d.shape

(3, 2)

In [37]:
_dict[1]

KeyError: 1